### ISSUE TITLE
btle_rx not working with HackRF

### ISSUE THREAD

**Issue by Sp3ctr3** [JiaoXianjun/BTLE#10]
Hi,

I've been trying to sniff the advertisement packets for a BLE Beacon as well as a BLE tracker using btle_rx. However I'm unable to capture any data even when specifying the exact channel of advertisement. However, these advertisement packets are being picked up by ubertooth-btle. I have tried changing the gain values and even specifying the frequency instead of the channel with no results. The RX LED of HackRF is lit up while running btle_rx.

Similarly for btle_tx, I've tried to transmitting the samples mentioned in the documentation. I'm unable to get the transmitted packets in ubertooth-btle. In case of iBeacon sample, my phone is unable to see it as well. The TX LED of HackRF is lit when running btle_tx.

Thanks!

**Comment by IlyaShaposhnikov** [comment]
Hi, same problem.

**Comment by JiaoXianjun** [comment]
Most cases, you need to adjust the gain setting. I confirm the tools work fine now.
