### ISSUE TITLE
BladeRF x40 TX

### ISSUE THREAD

**Issue by johndorry** [JiaoXianjun/BTLE#19]
Hi - I am using the btle_tx function with the BladeRF x40. There are no errors, however my packet sniffing tools do not see any packets, nor does my iBeacon scanner. Is there any configuration I am missing or is it because of an API change?

**Comment by JiaoXianjun** [comment]
Could you try different TX gain setting?

**Comment by JiaoXianjun** [comment]
It works well from my side. So I close this issue.
